config/routes.rb
Rails.application.routes.draw do
  root "markdowns#index"

  post 'markdowns/preview_api'
  resources :markdowns

  resources :users

  resources :sessions

end

app/models/markdown.rb
# -*- coding: utf-8 -*-
class Markdown
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :content

  def preview
    markdown = Redcarpet::Markdown.new Redcarpet::Render::HTML, \
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true

    # TODO: gsubは微妙...他にまともなやり方ありそう。
    markdown.render(content).gsub(/\n/, "").html_safe
  end
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword # for has_secure_password

  has_secure_password

  field :name
  field :email
  field :password_digest

  # validates :email,  presence: true, uniqueness: true
  # validates :password_digest,  presence: true


  attr_reader :password, :password_confirmation


end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  before_action :authorize

  def authorize
    unless session[:user_id]
      redirect_to \
        controller: :sessions,
        action: :new,
        alert: "まずはログインしましょう"

    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/markdowns_controller.rb
class MarkdownsController < ApplicationController
  before_action :set_markdown, only: [:show, :edit, :update, :destroy]

  # GET /markdowns
  # GET /markdowns.json
  def index
    @markdowns = Markdown.all
  end

  # GET /markdowns/1
  # GET /markdowns/1.json
  def show
  end

  # GET /markdowns/new
  def new
    @markdown = Markdown.new
  end

  # GET /markdowns/1/edit
  def edit
  end

  # POST /markdowns
  # POST /markdowns.json
  def create
    @markdown = Markdown.new(markdown_params)

    respond_to do |format|
      if @markdown.save
        format.html { redirect_to @markdown, notice: 'Markdown was successfully created.' }
        format.json { render :show, status: :created, location: @markdown }
      else
        format.html { render :new }
        format.json { render json: @markdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markdowns/1
  # PATCH/PUT /markdowns/1.json
  def update
    respond_to do |format|
      if @markdown.update(markdown_params)
        format.html { redirect_to @markdown, notice: 'Markdown was successfully updated.' }
        format.json { render :show, status: :ok, location: @markdown }
      else
        format.html { render :edit }
        format.json { render json: @markdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markdowns/1
  # DELETE /markdowns/1.json
  def destroy
    @markdown.destroy
    respond_to do |format|
      format.html { redirect_to markdowns_url, notice: 'Markdown was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def preview_api
    @preview = Markdown.new(markdown_params.tapp).tapp.preview
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_markdown
      @markdown = Markdown.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def markdown_params
      params.require(:markdown).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
# -*- coding: utf-8 -*-
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]

  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password]) # ココがポイント
      session[:user_id] = user.id.to_s # クソid対応
      redirect_to root_url, :notice => "Logged in!"
    else
      redirect_to new_session_path(alert: "なんか違う")
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end


  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdowns_helper.rb
module MarkdownsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markun</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/markdowns/_form.html.erb
<div id="preview_box">
  <%= form_for(@markdown) do |f| %>
    <div class="single_column">
      タイトル
      <%= f.text_area :title, class: :content%>
    </div>

    <div class="left_column">
      Markdown
      <%= f.text_area :content, class: :content %>
    </div>

    <div class="right_column">
      プレビュー
      <div id="preview" class="content border"></div>
    </div>

    <div class="clear">
      <%= f.submit %>
      <%= link_to 'チートシート', 'http://qiita.com/Qiita/items/c686397e4a0f4f11683d'%>
    </div>

  <% end %>
</div>

app/views/markdowns/edit.html.erb
<h1>編集のお時間です</h1>

<%= render 'form' %>

<%= link_to 'Show', @markdown %> |
<%= link_to 'Back', markdowns_path %>

app/views/markdowns/index.html.erb
<h1>Listing markdowns</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markdowns.each do |markdown| %>
      <tr>
        <td><%= markdown.title %></td>
        <td><%= markdown.content %></td>
        <td><%= link_to 'Show', markdown %></td>
        <td><%= link_to 'Edit', edit_markdown_path(markdown) %></td>
        <td><%= link_to 'Destroy', markdown, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'マークダウンつくろう', new_markdown_path %>
<%= link_to 'ログアウト', session_path(current_user), method: :delete %>

app/views/markdowns/new.html.erb
<h1>さぁ、マークダウンを書くのです！</h1>

<%= render 'form' %>
<%= link_to 'Back', markdowns_path %>

app/views/markdowns/preview_api.js.erb
$('#preview').html('<%= @preview %>')

app/views/markdowns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @markdown.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @markdown.content %>
</p>

<%= link_to 'Edit', edit_markdown_path(@markdown) %> |
<%= link_to 'Back', markdowns_path %>